# Generated by Django 5.0.4 on 2024-05-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date of the performance record.')),
                ('on_time_delivery_rate', models.FloatField(help_text='Historical record of the on-time delivery rate.')),
                ('quality_rating_avg', models.FloatField(help_text='Historical record of the quality rating average.')),
                ('average_response_time', models.FloatField(help_text='Historical record of the average response time.')),
                ('fulfillment_rate', models.FloatField(help_text='Historical record of the fulfilment rate.')),
                ('vendor', models.ForeignKey(help_text='Link to the Vendor model.', on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
